name: Jekyll Label Action
description: Automatically add labels depending on Jekyll front matter attributes
author: Pandapip1

inputs:
  token:
    description: GitHub token with repo permissions
    required: true
  config-path:
    description: Configuration file path
    default: .jekyll-labels.yml
    required: false

runs:
  using: node16
  main: dist/index.js

branding:
  icon: bookmark
  color: gray-dark
