on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
        with:
          persist-credentials: false
          fetch-depth: 0
      
      - name: Setup
        uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af # v4.1.0
        with:
          node-version: 16
      
      - name: Install
        run: npm ci

      - name: Build
        run: npm run build
      
      - name: Commit & Push changes
        uses: actions-js/push@5a7cbd780d82c0c937b5977586e641b2fd94acc5
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          message: Update dist/index.js; ${{ github.event.head_commit.message }}
          branch: dist
          force: true
