on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          persist-credentials: false
          fetch-depth: 0
      
      - name: Setup
        uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4.0.2
        with:
          node-version: 16
      
      - name: Install
        run: npm ci

      - name: Build
        run: npm run build
      
      - name: Commit & Push changes
        uses: actions-js/push@156f2b10c3aa000c44dbe75ea7018f32ae999772
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          message: Update dist/index.js; ${{ github.event.head_commit.message }}
          branch: dist
          force: true
