on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@8230315d06ad95c617244d2f265d237a1682d445 # v3.0.2
        with:
          persist-credentials: false
          fetch-depth: 0
      
      - name: Setup
        uses: actions/setup-node@c81d8ad96dab0a834a87f7a0300b154386f2e26a # v3.4.1
        with:
          node-version: 16
      
      - name: Install
        run: npm ci

      - name: Build
        run: npm run build
      
      - name: Commit & Push changes
        uses: actions-js/push@5f565701a8b9f9aa6b7efc25f28994eabfcf5312
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          message: Update dist/index.js; ${{ github.event.head_commit.message }}
          branch: dist
          force: true
