on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b # v3.2.0
        with:
          persist-credentials: false
          fetch-depth: 0
      
      - name: Setup
        uses: actions/setup-node@8c91899e586c5b171469028077307d293428b516 # v3.5.1
        with:
          node-version: 16
      
      - name: Install
        run: npm ci

      - name: Build
        run: npm run build
      
      - name: Commit & Push changes
        uses: actions-js/push@156f2b10c3aa000c44dbe75ea7018f32ae999772
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          message: Update dist/index.js; ${{ github.event.head_commit.message }}
          branch: dist
          force: true
