on:
  push:
    branches:
      - dist

jobs:
  deploy:
    name: Create Release
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Automatic GitHub Release
        uses: justincy/github-action-npm-release@e237b4afa029f7982eaa6fafeace8343e902de4e
